FROM apache/airflow:latest

USER root

# Set working directory explicitly
WORKDIR /opt/airflow

# Copy requirements and install Python packages
COPY requirements.txt /opt/airflow/



RUN apt-get update && \
    apt-get -y install git && \
    apt-get clean

USER airflow
RUN pip install --no-cache-dir -r requirements.txt
